## Generated 100 sequences of 1,000 states based on PI and  A
### Markov model with three states, S1, S2, S3, initial probabilities 
#### PI= [0.5,0.2,0.3] and  A= [0.4   0.3   0.3          0.2    0.6   0.2           0.1    0.1   0.8]

In [1]:
import numpy as np
import random as rm

In [2]:
# The statespace
states = ["S1","S2","S3"]

# initial state probabilities
PI= [0.5, 0.2, 0.3]

# Possible sequences of events based on states
transitionName = [["S1S1","S1S2","S1S3"],["S2S2","S2S1","S2S3"],["S3S1","S3S3","S3S2"]]

# Transition matrix
A = [[0.4,0.3,0.3],[0.2,0.6,0.2],[0.1,0.1,0.8]]

In [3]:
if sum(A[0])+sum(A[1])+sum(A[1]) != 3:
    print("Probablity Sum Transition Matrix went wrong!")
else: print("Hidden Markov Model!!!!!")

Hidden Markov Model!!!!!


## Generated Data based on PI and A

In [4]:
def state_list(st):
    # Choose the starting state
    initial_state = np.random.choice(states,replace=True,p=PI)
    #print(initial_state)
    
    start_List = [initial_state]
    i = 0
    prob = 1
    while i != st:
        if initial_state == "S1":
            change = np.random.choice(transitionName[0],replace=True,p=A[0])
            if change == "S1S1":
                prob = prob * 0.4
                start_List.append("S1")
                pass
            elif change == "S1S2":
                prob = prob * 0.3
                initial_state = "S2"
                start_List.append("S2")
            else:
                prob = prob * 0.3
                initial_state = "S3"
                start_List.append("S3")
        elif initial_state == "S2":
            change = np.random.choice(transitionName[1],replace=True,p=A[1])
            if change == "S2S2":
                prob = prob * 0.2
                start_List.append("S2")
                pass
            elif change == "S2S1":
                prob = prob * 0.6
                initial_state = "S1"
                start_List.append("S1")
            else:
                prob = prob * 0.2
                initial_state = "S3"
                start_List.append("S3")
        elif initial_state == "S3":
            change = np.random.choice(transitionName[2],replace=True,p=A[2])
            if change == "S3S3":
                prob = prob * 0.1
                start_List.append("S3")
                pass
            elif change == "S3S1":
                prob = prob * 0.1
                initial_state = "S1"
                start_List.append("S1")
            else:
                prob = prob * 0.8
                initial_state = "S2"
                start_List.append("S2")
        i += 1    
    return start_List

# To save every state list
list_states = []
count = 0

# Starts range from the first count up until but excluding the last count
for iterations in range(0,100):
        list_states.append(state_list(999))



In [5]:
print("Generated 100 Sequence of 1000 States :", list_states)
#print(list_states)

Generated 100 Sequence of 1000 States : [['S1', 'S3', 'S2', 'S1', 'S1', 'S1', 'S1', 'S1', 'S3', 'S2', 'S1', 'S2', 'S1', 'S2', 'S1', 'S1', 'S1', 'S3', 'S2', 'S1', 'S3', 'S3', 'S1', 'S3', 'S2', 'S1', 'S3', 'S1', 'S1', 'S3', 'S2', 'S1', 'S2', 'S2', 'S2', 'S3', 'S2', 'S1', 'S3', 'S2', 'S1', 'S3', 'S2', 'S3', 'S2', 'S2', 'S2', 'S1', 'S1', 'S1', 'S2', 'S3', 'S2', 'S1', 'S2', 'S2', 'S1', 'S1', 'S1', 'S2', 'S1', 'S2', 'S3', 'S2', 'S2', 'S3', 'S3', 'S1', 'S1', 'S1', 'S2', 'S1', 'S2', 'S2', 'S3', 'S2', 'S1', 'S2', 'S1', 'S1', 'S3', 'S2', 'S3', 'S2', 'S1', 'S3', 'S2', 'S1', 'S2', 'S1', 'S1', 'S2', 'S2', 'S1', 'S3', 'S2', 'S1', 'S2', 'S1', 'S1', 'S3', 'S2', 'S1', 'S2', 'S1', 'S1', 'S1', 'S1', 'S2', 'S1', 'S3', 'S2', 'S3', 'S2', 'S1', 'S2', 'S1', 'S1', 'S2', 'S3', 'S2', 'S1', 'S1', 'S2', 'S2', 'S2', 'S3', 'S2', 'S2', 'S1', 'S1', 'S2', 'S2', 'S1', 'S3', 'S2', 'S1', 'S3', 'S2', 'S2', 'S1', 'S3', 'S3', 'S2', 'S1', 'S1', 'S3', 'S2', 'S1', 'S2', 'S2', 'S1', 'S2', 'S3', 'S3', 'S2', 'S1', 'S1', 'S2', 'S1'

In [6]:
print("Total Sequence: ", len(list_states))

Total Sequence:  100


## Estimated PI and A after generating 100 sequences of 1,000 states

### Estimatation of PI

In [7]:
import numpy as np
PI= np.zeros(len(states), dtype="float64")
#print(PI)
for i in range(0, len(list_states)):
    for s in list_states[i]:
        PI[states.index(s)] +=1

#PI
PI= PI/sum(PI)
print("Start Probablity of PI after generating Data : ", PI)
#print(PI)
print("Sum of three states",sum(PI))

Start Probablity of PI after generating Data :  [0.40984 0.37175 0.21841]
Sum of three states 1.0


In [8]:
# to find index
STATE_SIZE=len(states)
#print(STATE_SIZE)
sequence_length= len(list_states)
print("Total Sequence: ",sequence_length)

Total Sequence:  100


### Estimatation Of Transition Matrix A

In [9]:
A_transition= np.zeros((STATE_SIZE, STATE_SIZE))

for k in range(0, len(list_states)):
    for s in range(1, len(list_states[k])):
        i = states.index(list_states[k][s - 1])
        j = states.index(list_states[k][s])
        A_transition[i, j] += 1
        
A_transition

array([[16445., 12257., 12235.],
       [22320.,  7409.,  7409.],
       [ 2173., 17482.,  2170.]])

In [10]:
rowSum = np.sum(A_transition, 1)
rowSum

array([40937., 37138., 21825.])

In [11]:
B=(A_transition.T/rowSum).T
rowSumB=np.sum(B,1)
rowSumB

A_transition=B
A_transition

array([[0.40171483, 0.29941129, 0.29887388],
       [0.60100167, 0.19949917, 0.19949917],
       [0.09956472, 0.80100802, 0.09942726]])

# Building HMM and generating samples By using HMMLearn library 

## Importing HMMLearn library 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from hmmlearn import hmm

## Question Answer 1.a: Generated 100 sequences of 1,000 states based on PI and  A by using HMMLearn library functions


In [2]:
startprob_ = np.array([0.5, 0.2, 0.3])
# The transition matrix, note that there are no transitions possible
# between component 1 and 3
transmat_ = np.array([[0.4, 0.3, 0.3], 
                    [0.2, 0.6, 0.2], 
                    [0.1, 0.1, 0.8]])


# The means of each component
means = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
# The covariance of each component
covars = np.tile(np.identity(2), (3, 1, 1))

# Build an HMM instance and set parameters
model = hmm.GaussianHMM(n_components=3,n_iter=1000,covariance_type="full")

# Instead of fitting it from the data, we directly set the estimated
# parameters, the means and covariance of the components
model.startprob_ = startprob_
model.transmat_ = transmat_
model.means_ = means
model.covars_ = covars

In [3]:
# Generate samples
X, Z = model.sample(100)

In [4]:
print(len(X))

100


## Fitting HMMLearn library for sample 100 sequences of 1,000 states.

In [5]:
remodel = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=1000)
remodel.fit(X)

GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
            covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
            min_covar=0.001, n_components=3, n_iter=1000, params='stmc',
            random_state=None, startprob_prior=1.0, tol=0.01,
            transmat_prior=1.0, verbose=False)

In [6]:
Z2 = remodel.predict(X) # hidden state sequence

In [7]:
remodel.monitor_

ConvergenceMonitor(
    history=[-362.9293739706088, -362.92690659020224],
    iter=11,
    n_iter=1000,
    tol=0.01,
    verbose=False,
)

In [8]:
remodel.sample(100) # observation sequence

(array([[ 0.19072783, -1.7692386 ],
        [ 4.99333659,  9.95604387],
        [ 5.56794229,  9.85012707],
        [ 4.19532503, 11.0061335 ],
        [ 4.70433678,  9.03190008],
        [ 5.48790685, 10.06481256],
        [ 3.39578863, 10.82062628],
        [-0.71088298, -0.31875491],
        [ 0.44591993, -1.17517086],
        [ 6.11905707,  9.27439553],
        [ 5.8171193 , 10.2005835 ],
        [ 4.80518539, 11.35049519],
        [ 0.1565604 ,  0.07145602],
        [ 2.31664899, -0.19285019],
        [ 1.04970068, -0.51146175],
        [-0.68392339, -0.74215558],
        [ 1.12009493, -0.66371879],
        [ 2.7216903 , -3.40058076],
        [ 3.27211178, -1.89633089],
        [ 2.94573791, -2.92022961],
        [ 2.90360526, -2.94402902],
        [ 2.38683797, -1.7072939 ],
        [ 3.47192355, -1.41138148],
        [ 3.02073852, -0.70254351],
        [ 6.05521322,  8.56703802],
        [ 5.53228578,  9.57956882],
        [ 5.5275784 ,  9.09473034],
        [ 5.56433457, 12.333

### Estimatation of PI

In [9]:
print("HMM Start Probablity PI: ", remodel.startprob_)

HMM Start Probablity PI:  [1.00000000e+000 9.35406607e-271 4.23800680e-068]


### Estimatation Of Transition Matrix A

In [10]:
print("Transition matrix A", remodel.transmat_)


Transition matrix A [[0.47817455 0.33752638 0.18429907]
 [0.10410397 0.74074074 0.15515529]
 [0.07044074 0.3308983  0.59866096]]
